
 export default function generateName(){
	var first_name =  [
		"Liam",
		"Emma",
		"Noah",
		"Olivia",
		"Sophia",
		"Jackson",
		"Ava",
		"Lucas",
		"Isabella",
		"Mia",
		"Oliver",
		"Amelia",
		"Elijah",
		"Harper",
		"Charlotte",
		"William",
		"Luna",
		"Aiden",
		"Evelyn",
		"James",
		"Mila",
		"Benjamin",
		"Aria",
		"Henry",
		"Scarlett",
		"Michael",
		"Chloe",
		"Alexander",
		"Lily",
		"Ethan",
		"Zoe",
		"Daniel",
		"Camila",
		"Matthew",
		"Layla",
		"Joseph",
		"Grace",
		"David",
		"Nora",
		"Carter",
		"Aubrey",
		"Jacob",
		"Emily",
		"Logan",
		"Hannah",
		"Sebastian",
		"Addison",
		"Muhammad",
		"Elizabeth",
		"Jayden",
		"Victoria",
		"William",
		"Penelope",
		"James",
		"Sofia",
		"Alexander",
		"Avery",
		"Henry",
		"Ella",
		"Michael",
		"Ariana",
		"Elijah",
		"Scarlett",
		"Daniel",
		"Riley",
		"Matthew",
		"Hazel",
		"Benjamin",
		"Aurora",
		"William",
		"Zoey",
		"Ethan",
		"Abigail",
		"James",
		"Lily",
		"Oliver",
		"Eleanor",
		"Daniel",
		"Nora",
		"Ethan",
		"Hannah",
		"Aiden",
		"Madison",
		"Michael",
		"Bella",
		"William",
		"Layla",
		"Oliver",
		"Chloe",
		"Elijah",
		"Ellie",
		"Oliver",
		"Lily",
		"Oliver",
		"Zoe",
		"William",
		"Stella",
		"Benjamin",
		"Paisley",
	  ];

	var last_name =  [
		"Smith",
		"Johnson",
		"Brown",
		"Taylor",
		"Miller",
		"Anderson",
		"Thomas",
		"Jackson",
		"White",
		"Harris",
		"Martin",
		"Thompson",
		"Garcia",
		"Martinez",
		"Robinson",
		"Clark",
		"Rodriguez",
		"Lewis",
		"Lee",
		"Walker",
		"Hall",
		"Allen",
		"Young",
		"Hernandez",
		"King",
		"Wright",
		"Lopez",
		"Hill",
		"Scott",
		"Green",
		"Adams",
		"Baker",
		"Gonzalez",
		"Nelson",
		"Carter",
		"Mitchell",
		"Perez",
		"Roberts",
		"Turner",
		"Phillips",
		"Campbell",
		"Parker",
		"Evans",
		"Edwards",
		"Collins",
		"Stewart",
		"Sanchez",
		"Morris",
		"Rogers",
		"Reed",
		"Cook",
		"Morgan",
		"Bell",
		"Murphy",
		"Bailey",
		"Rivera",
		"Cooper",
		"Richardson",
		"Cox",
		"Howard",
		"Ward",
		"Torres",
		"Peterson",
		"Gray",
		"Ramirez",
		"James",
		"Watson",
		"Brooks",
		"Kelly",
		"Sanders",
		"Price",
		"Bennett",
		"Wood",
		"Barnes",
		"Ross",
		"Henderson",
		"Coleman",
		"Jenkins",
		"Perry",
		"Powell",
		"Long",
		"Patterson",
		"Hughes",
		"Flores",
		"Washington",
		"Butler",
		"Simmons",
		"Foster",
		"Gonzales",
		"Bryant",
		"Alexander",
		"Russell",
		"Griffin",
		"Diaz",
		"Hayes",
		"Myers",
		"Ford",
	  ];
	  

	var name = first_name[Math.floor(Math.random() * 100)]+' '+last_name[Math.floor(Math.random() * 100)];
	return name;

}



export function generateRandomString() {
    const var3=[
		"Amazing! 👍",
		"Beautiful 😍",
		"Love this! ❤️",
		"Great stream! 🎉",
		"Awesome content! 🚀",
		"Keep it up! 💪",
		"You're doing great! 🙌",
		"Loving the vibes! 🎵",
		"This is so much fun! 🤩",
		"I'm enjoying this a lot! 😄",
		"You're killing it! 🔥",
		"Super cool! 😎",
		"Incredible performance! 🤯",
		"Such a talented host! 🌟",
		"This is top-notch! 🏆",
		"Thumbs up! 👍👍",
		"Heartwarming! ❤️",
		"Bravo! 👏",
		"Impressive skills! 👌",
		"I can't stop watching! 🤓",
		"Mind-blowing! 🤩",
		"You make it look easy! 😄",
		"So entertaining! 🍿",
		"I'm hooked! 🎣",
		"This is gold! 🏅",
		"You're an inspiration! 💫",
		"This deserves more views! 🌟",
		"Best stream ever! 🌈",
		"You rock! 🤘",
		"I'm loving the chat! 💬",
		"I'm having a blast! 🎉",
		"Epic performance! 🎭",
		"You're a legend! 🏆",
		"So much talent! 🌟",
		"I can't get enough! 😍",
		"Well done! 👍",
		"You're awesome! 😎",
		"This is addictive! 💻",
		"My new favorite channel! 📺",
		"Unbelievable! 🙀",
		"Fantastic work! 👏",
		"Hats off to you! 🎩",
		"You're on fire! 🔥",
		"This is pure gold! 💰",
		"You've got a new fan! 🎉",
		"Mind-blowing skills! 🤯",
		"You're a true talent! 🌟",
		"I can't stop watching! 😲",
		"Such a creative host! 🎨",
		"You've got me hooked! 🎣",
		"Outstanding performance! 🏆",
		"I'm inspired! 💡",
		"You deserve all the likes! 👍",
		"Astonishing! 😱",
		"You're incredible! 🤩",
		"You're a pro! 🏅",
		"I'm glued to the screen! 📺",
		"This is legendary! 🌟",
		"You're a superstar! 🌟",
		"So much talent in one place! 🎭",
		"I'm in awe! 😍",
		"Absolutely brilliant! 🌟",
		"You're on another level! 🔝",
		"This is mind-blowing! 🤯",
		"You're an amazing host! 🌟",
		"I can't get enough of this! 🤤",
		"You nailed it! 👌",
		"This is perfection! 💯",
		"You've got a gift! 🎁",
		"You're making my day! 🌞",
		"This is next-level content! 🚀",
		"You're a wizard! 🧙‍♂️",
		"Impressive stuff! 👍",
		"You're a shining star! ✨",
		"I'm so impressed! 😲",
		"This is outstanding! 🏆",
		"You're a master! 🎓",
		"I'm loving every minute! ⌛",
		"This is spectacular! 🌈",
		"You've got the magic touch! ✨",
		"You're a champ! 🏆",
		"This is absolutely top-notch! 👌",
		"You're killing it, as always! 🔥",
		"I can't look away! 👀",
		"You're one in a million! 💯",
		"This is pure talent! 🌟",
		"You're a force to be reckoned with! 💪",
		"This is amazing work! 🎨",
		"You're making history! 📜",
		"This is a masterpiece! 🎨",
		"You've got me hooked for life! 🎣",
		"You're a true entertainer! 🎭",
		"This is magic! ✨",
		"You're a legend in the making! 🌟",
		"I'm cheering you on! 🎉",
		"This is brilliance! 💡",
		"You're destined for greatness! 🌟",
		"You're unstoppable! 🚀",
		"This is a game-changer! 🎮",
		"You're a true artist! 🎨",
		"This is a masterpiece in the making! 🌠",
		"You're a shining example! ☀️",
		"This is a work of art! 🎨",
		"You're leaving me speechless! 😶",
		"This is excellence! 👌",
		"You're an inspiration to us all! 🌟",
		"This is pure joy! 😄",
		"You're a creative genius! 🧠",
		"This is outstanding content! 🏆",
		"You're a trendsetter! 📈",
		"This is beyond impressive! 🌟",
		"You're a star in the making! ⭐",
		"This is captivating! 📚",
		"You're on the right path! 🛤️",
		"This is legendary content! 🏆",
		"You're making dreams come true! 🌌",
		"This is top-tier entertainment! 🎬",
		"You're a true original! 🌟",
		"This is top-notch stuff! 👍",
		"You're destined for greatness! 🏅",
	  ];
    let result = '';
    let i=Math.floor(Math.random() * 100);
	result =var3[i]; 
    
    return result;
}
